export const GET_GAME_BEGIN = "GET_GAME_BEGIN";
export const GET_GAME_SUCCESS = "GET_GAME_SUCCESS";
export const GET_GAME_FAIL = "GET_GAME_FAIL";

export const GET_DETAIL_GAME_BEGIN = "GET_DETAIL_GAME_BEGIN";
export const GET_DETAIL_GAME_SUCCESS = "GET_DETAIL_GAME_SUCCESS";
export const GET_DETAIL_GAME_FAIL = "GET_DETAIL_GAME_FAIL";

export const GET_GAME_GENRE_BEGIN = "GET_GAME_GENRE_BEGIN";
export const GET_GAME_GENRE_SUCCESS = "GET_GAME_GENRE_SUCCESS";
export const GET_GAME_GENRE_FAIL = "GET_GAME_GENRE_FAIL";
